FROM ubuntu:latest

# Install Python
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Set working dir inside container
WORKDIR /app

# Copy requirements and install them
COPY ../requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir --break-system-packages -r requirements.txt

# Copy the rest of the app
COPY .. /app

# Expose Flask port 
EXPOSE 5000

CMD ["tail", "-f", "/dev/null"]
